name: diplodatos-graphs
channels:
  - conda-forge
  - giuliorossetti
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn=0.11
  - scikit-learn
  - nltk
  - networkx
  - wordcloud
  - pip
  - pip:
    - cdlib
